services:
  xqtl-explorer-service:
    container_name: ${CONTAINER_NAME}
    image: ${CONTAINER_NAME}
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./client.Dockerfile     
      args:
          BUILD: ${BUILD} 
          GIT_DEPENDENCIES: ${GIT_DEPENDENCIES}

    ports:
      - '${PORT}:3000'
    volumes:
      - ${APPLICATION_DIR}:/app
      # by mounting the "node_modules" we force it to be empty
      # and keep the docker container from finding node_modules installed on the host
      # https://github.com/Kartikdot/TS-Node-Docker-Starter/blob/main/docker-compose.yaml
      - ignore:/app/node_modules
    networks:
      - nextjs-app

networks:
  nextjs-app:
    name: niagads-service-network 
    external: true

volumes:
  ignore: 


# see https://github.com/ErickWendel/livereload-docker-nodejs-typescript/blob/master/Dockerfile